name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [ labeled ]

# Setting the shell option, it will run 'bash --noprofile --norc -eo pipefail {0}'
defaults:
  run:
    shell: bash

jobs:
  build-docker:
    name: Build and push Docker image to GitHub Container Registry
    if: ${{ github.ref == 'refs/heads/main' }} || ${{ github.event.label.name == 'nix' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: jellyvr
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - name: "Build Docker image"
        run: nix build .#dockerImage
      - run: docker load --input ./result
      - name: "Push Docker image to GitHub Container Registry"
        run: docker push ghcr.io/alyti/jellyvr:$(docker images jellyvr --format {{.Tag}})
